# Generated by Django 4.0.4 on 2022-06-14 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie_centra', models.CharField(max_length=150, verbose_name='Название центра')),
                ('adres', models.CharField(max_length=150, verbose_name='Адрес')),
                ('familiya_direktora', models.CharField(max_length=50, verbose_name='Фамилия директора')),
                ('imya_direktora', models.CharField(max_length=50, verbose_name='Имя директора')),
                ('otchestvo_direktora', models.CharField(max_length=50, verbose_name='Отчество директора')),
                ('kontakt_telefon', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('elektronnaya_pochta', models.CharField(max_length=50, verbose_name='Элктронная почта')),
            ],
            options={
                'verbose_name': 'Центр',
                'verbose_name_plural': 'Центры',
                'db_table': 'centr',
            },
        ),
        migrations.CreateModel(
            name='Date_platnye_uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата услуги')),
            ],
            options={
                'verbose_name': 'Дата платной услуги',
                'verbose_name_plural': 'Даты платных услуг',
                'db_table': 'date_platnye_uslugi',
            },
        ),
        migrations.CreateModel(
            name='Login_parol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('parol', models.CharField(max_length=50, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Логин и пароль',
                'verbose_name_plural': 'Логины и пароли',
                'db_table': 'login_parol',
            },
        ),
        migrations.CreateModel(
            name='Obuch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('imya', models.CharField(max_length=50, verbose_name='Имя')),
                ('otchestvo', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('nazvanie_shkoly', models.CharField(max_length=150, verbose_name='Название школы')),
                ('adres_shkoly', models.CharField(max_length=150, verbose_name='Адрес школы')),
                ('elektronnaya_pochta', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('klass', models.CharField(max_length=20, verbose_name='Класс')),
                ('nomer_telefona', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('id_centra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.centr', verbose_name='ID центра')),
                ('id_logina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.login_parol', verbose_name='ID логина и пароля')),
            ],
            options={
                'verbose_name': 'Обучающийся',
                'verbose_name_plural': 'Обучающиеся',
                'db_table': 'obuch',
            },
        ),
        migrations.CreateModel(
            name='Prepod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('imya', models.CharField(max_length=50, verbose_name='Имя')),
                ('otchestvo', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('elektronnaya_pochta', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('nomer_telefona', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('id_centra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.centr', verbose_name='ID центра')),
                ('id_logina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.login_parol', verbose_name='ID логина и пароля')),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподователи',
                'db_table': 'prepod',
            },
        ),
        migrations.CreateModel(
            name='Proekty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie_proekta', models.CharField(max_length=50, verbose_name='Название проекта')),
                ('opisanie_proekta', models.TextField(verbose_name='Описание проекта')),
                ('id_centra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.centr', verbose_name='ID центра')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'proekty',
            },
        ),
        migrations.CreateModel(
            name='Programmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razdel', models.CharField(max_length=50, verbose_name='Раздел')),
                ('nazvanie_programmy', models.CharField(max_length=50, verbose_name='Название программы')),
                ('opisanie', models.TextField(verbose_name='Описание')),
                ('id_prepod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.prepod', verbose_name='ID преподователя')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'db_table': 'programmy',
            },
        ),
        migrations.CreateModel(
            name='Zapisanye_na_ptogtammu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_zapisi', models.DateField(verbose_name='Дата записи')),
                ('id_obuch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.obuch', verbose_name='ID обучающего')),
                ('id_prog', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.programmy', verbose_name='ID программы')),
            ],
            options={
                'verbose_name': 'Зарисанный на программу',
                'verbose_name_plural': 'Зарисанные на программу',
                'db_table': 'zapisanye_na_ptogtammu',
            },
        ),
        migrations.CreateModel(
            name='Spisok_proekta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_obuch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.obuch', verbose_name='ID обучающего')),
                ('id_prepod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.prepod', verbose_name='ID преподователя')),
                ('id_proekta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.proekty', verbose_name='ID проекта')),
            ],
            options={
                'verbose_name': 'Список в проекте',
                'verbose_name_plural': 'Список в проекте',
                'db_table': 'spisok_proekta',
            },
        ),
        migrations.CreateModel(
            name='Sotrudniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('imya', models.CharField(max_length=50, verbose_name='Имя')),
                ('otchestvo', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('elektronnaya_pochta', models.CharField(max_length=20, verbose_name='Электронная почта')),
                ('nomer_telefona', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('id_centra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.centr', verbose_name='ID центра')),
                ('id_logina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.login_parol', verbose_name='ID логина и пароля')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'sotrudniki',
            },
        ),
        migrations.CreateModel(
            name='Platnye_uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razdel', models.CharField(max_length=50, verbose_name='Раздел')),
                ('nazvanie_uslugi', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('opisanie_uslugi', models.TextField(verbose_name='Описание услуги')),
                ('id_centra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.centr', verbose_name='ID центра')),
                ('id_date', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.date_platnye_uslugi', verbose_name='ID даты')),
            ],
            options={
                'verbose_name': 'Платная услуга',
                'verbose_name_plural': 'Платные услуги',
                'db_table': 'platnye_uslugi',
            },
        ),
        migrations.CreateModel(
            name='Partery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=150, verbose_name='Партенра')),
                ('opisanie', models.TextField(verbose_name='Описаник')),
                ('id_centra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.centr', verbose_name='ID центра')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'db_table': 'partery',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie_news', models.CharField(max_length=50, verbose_name='Название новости')),
                ('news', models.TextField(verbose_name='Новасть')),
                ('date', models.DateField(verbose_name='Дата новости')),
                ('id_centra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.centr', verbose_name='ID центра')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Meropriyatya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=50, verbose_name='Вид')),
                ('nazvanie_meropriyatya', models.CharField(max_length=50, verbose_name='Название мероприятия')),
                ('opisanie_meropriyatya', models.TextField(verbose_name='Описаник мероприятия')),
                ('plan', models.TextField(verbose_name='План')),
                ('id_centra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.centr', verbose_name='ID центра')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'meropriyatya',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie_case', models.CharField(max_length=50, verbose_name='Название кейса')),
                ('opisanie_case', models.TextField(verbose_name='Описание кейса')),
                ('ssilka', models.CharField(max_length=150, verbose_name='Ссылка для скачивания кейса')),
                ('id_centra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.centr', verbose_name='ID центра')),
            ],
            options={
                'verbose_name': 'Кейс от партнера',
                'verbose_name_plural': 'Кейсы от партнеров',
                'db_table': 'case',
            },
        ),
    ]
