from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_admin, name='home_admin'),
    path('merop_admin', views.merop_admin, name='merop_admin'),
    path('merop_admin/merop_kon_admin', views.merop_kon_admin, name='merop_kon_admin'),
    path('merop_admin/merop_ne_kon_admin', views.merop_ne_kon_admin, name='merop_ne_kon_admin'),
    path('part_admin', views.part_admin, name='part_admin'),
    path('plat_admin', views.plat_admin, name='plat_admin'),
    path('plat_admin/plat_eks_admin', views.plat_eks_admin, name='plat_eks_admin'),
    path('plat_admin/plat_fab_admin', views.plat_fab_admin, name='plat_fab_admin'),
    path('plat_admin/plat_mer_admin', views.plat_mer_admin, name='plat_mer_admin'),
    path('plat_admin/plat_prog_admin', views.plat_prog_admin, name='plat_prog_admin'),
    path('plat_admin/plat_prog_admin/plat_prog_dosh_admin', views.plat_prog_dosh_admin, name='plat_prog_dosh_admin'),
    path('plat_admin/plat_prog_admin/plat_prog_nach_admin', views.plat_prog_nach_admin, name='plat_prog_nach_admin'),
    path('prepod_admin', views.prepod_admin, name='prepod_admin'),
    path('program_admin', views.program_admin, name='program_admin'),
    path('program_admin/program_det_admin', views.program_det_admin, name='program_det_admin'),
    path('program_admin/program_mal_admin', views.program_mal_admin, name='program_mal_admin'),
    path('program_admin/program_set_admin', views.program_set_admin, name='program_set_admin'),
    path('case_admin', views.case_admin, name='case_admin'),
    path('fun_ad', views.fun_ad, name='fun_ad'),
    path('fun_ad/news/dob_news', views.dob_news, name='dob_news'),
    path('fun_ad/news/<int:pk>', views.Datel_news.as_view(), name='news-detail'),
    path('fun_ad/news/<int:pk>/izmen', views.Izmen_news.as_view(), name='news-izmen'),
    path('fun_ad/news/<int:pk>/delete', views.Delete_news.as_view(), name='news-delete'),
    path('fun_ad/prog/<int:pk>', views.Datel_prog.as_view(), name='prog-detail'),
    path('fun_ad/prog/dob_prog', views.dob_prog, name='dob_prog'),
    path('fun_ad/prog/<int:pk>/izmen', views.Izmen_prog.as_view(), name='prog-izmen'),
    path('fun_ad/prog/<int:pk>/delete', views.Delete_prog.as_view(), name='prog-delete'),
    path('fun_ad/merop/dob_merop', views.dob_merop, name='dob_merop'),
    path('fun_ad/merop/<int:pk>', views.Datel_merop.as_view(), name='merop-detail'),
    path('fun_ad/merop/<int:pk>/izmen', views.Izmen_merop.as_view(), name='merop-izmen'),
    path('fun_ad/merop/<int:pk>/delete', views.Delete_merop.as_view(), name='merop-delete'),
    path('fun_ad/plat/dob_plat', views.dob_plat, name='dob_plat'),
    path('fun_ad/plat/<int:pk>', views.Datel_plat.as_view(), name='plat-detaili'),
    path('fun_ad/plat/<int:pk>/izmen', views.Izmen_plat.as_view(), name='plat-izmen'),
    path('fun_ad/plat/<int:pk>/delete', views.Delete_plat.as_view(), name='plat-delete'),
]